# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def pods
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'glog', :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec"

    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'ART',
      'CxxBridge',
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTActionSheet',
      'RCTAnimation',
      'RCTBlob',
      'RCTCameraRoll',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTPushNotification',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket', # needed for debugging
      # Add any other subspecs you want to use in your project
    ]
    
    # react-native-maps dependencies
    pod 'react-native-maps', path: '../node_modules/react-native-maps'
    pod 'react-native-google-maps', path: '../node_modules/react-native-maps'  # Uncomment this line if you want to support GoogleMaps on iOS
    pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
    pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS

end


target 'SharePlaces' do
  pods
end

target 'SharePlacesTests' do
  pods
end